version: 2

models:
  - name: dim_customer
    description: "Customer dimension"
    columns:
      - name: customer_key
        description: "Natural customer key from source"
        tests:
          - unique
          - not_null
      - name: customer_name
        tests:
          - not_null
      - name: address
        tests:
          - not_null
      - name: phone_number
        tests:
          - not_null
      - name: market_segment
        tests:
          - not_null

  - name: dim_date
    description: "Date dimension derived from order_date"
    columns:
      - name: date_key
        description: "Date key (date of order)"
        tests:
          - unique
          - not_null
      - name: year
        tests:
          - not_null
      - name: quarter
        tests:
          - not_null
      - name: month
        tests:
          - not_null
      - name: day_of_week
        tests:
          - not_null

  - name: fact_orders
    description: "Fact table at the order grain"
    columns:
      - name: order_key
        description: "Surrogate PK for each order"
        tests:
          - unique
          - not_null

      - name: order_id
        description: "Natural order identifier"
        tests:
          - not_null

      - name: customer_key
        description: "FK → dim_customer.customer_key"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_key

      - name: date_key
        description: "FK → dim_date.date_key"
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key

      - name: order_status
        tests:
          - not_null

      - name: total_price
        tests:
          - not_null
          - positive_value

      - name: priority
        tests:
          - not_null

      - name: part_id
        tests:
          - not_null

      - name: supplier_id
        tests:
          - not_null

      - name: quantity
        tests:
          - not_null

      - name: extended_price
        tests:
          - not_null

      - name: discount
        tests:
          - not_null

      - name: tax
        tests:
          - not_null

      - name: return_flag
        tests:
          - not_null

      - name: line_status
        tests:
          - not_null
